---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-image:tag
      ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
spec:
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
