apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-demo
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-demo
    spec:
      containers:
        - image: apaspxp/jenkins-demo:latest
          name: jenkins-demo
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-demo
  name: jenkins-demo
spec:
  ports:
    - name: 7777-7777
      port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: jenkins-demo
  type: NodePort
status:
  loadBalancer: {}
